# Generated by Django 4.1.4 on 2023-01-04 04:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exercise', models.CharField(choices=[('Push-up', 'Push-up'), ('Flapping-Cross', 'Flapping-Cross')], default='Push-up', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Workout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime_performed', models.DateTimeField()),
                ('num_sets', models.IntegerField()),
                ('num_reps', models.IntegerField()),
                ('exercise_performed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.exercise')),
                ('performed_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
