# Generated by Django 4.1.4 on 2023-01-05 00:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exercise',
            old_name='exercise',
            new_name='name',
        ),
    ]
