# Generated by Django 4.1.4 on 2023-01-07 19:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('web', '0002_rename_exercise_exercise_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExerciseSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime_performed', models.DateTimeField()),
                ('num_reps', models.IntegerField()),
                ('exercise_performed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.exercise')),
                ('performed_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Workout',
        ),
    ]
