# Generated by Django 4.1.4 on 2023-02-03 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_exerciseset_delete_workout'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='measurement_type',
            field=models.CharField(choices=[('Second', 'Second'), ('Cycle', 'Cycle')], default='Cycle', max_length=30),
        ),
    ]
