# Generated by Django 4.1.4 on 2023-02-09 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_exerciseset_delete_workout'),
    ]

    operations = [
        migrations.AddField(
            model_name='exerciseset',
            name='duration_seconds',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='exercise',
            name='name',
            field=models.CharField(choices=[('Push-up', 'Push-up'), ('Flapping-Cross', 'Flapping-Cross'), ('Plank', 'Plank')], default='Push-up', max_length=30),
        ),
    ]
