# Generated by Django 4.1.4 on 2023-02-03 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_exercise_measurement_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='name',
            field=models.CharField(choices=[('Push-up', 'Push-up'), ('Flapping-Cross', 'Flapping-Cross'), ('Plank', 'Plank')], default='Push-up', max_length=30),
        ),
    ]
