# Generated by Django 4.1.4 on 2023-03-25 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_exerciseset_duration_seconds_alter_exercise_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='exerciseset',
            name='duration_target_seconds',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='exerciseset',
            name='num_target_reps',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
