# Generated by Django 4.1.4 on 2023-02-03 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_alter_exercise_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exerciseset',
            name='num_reps',
        ),
        migrations.AddField(
            model_name='exerciseset',
            name='measurement',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
    ]
