# Generated by Django 4.1.4 on 2023-03-25 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_exerciseset_duration_target_seconds_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='name',
            field=models.CharField(choices=[('Push-up', 'Push-up'), ('Flapping-Cross', 'Flapping-Cross'), ('Plank', 'Plank'), ('Standing-Cross', 'Standing-Cross')], default='Push-up', max_length=30),
        ),
    ]
